// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kffsqqzupqbxfrarfvak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmZnNxcXp1cHFieGZyYXJmdmFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5ODAzMzgsImV4cCI6MjA1MDU1NjMzOH0.-3THJRHuGgTkCXW4ch4sc_YUV0qYFqPIj9Nm4n0YeEk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);